---
title: "Vision and Scope Document: Next Great Project"
author: "(Author)"
date: "(Date)"
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Business Requirements

### Problem Definition

What's the pain point, experienced by what customers? 
What's the _gap_ between current and future states of being?
Situation's properties: market dynamics, trends, competition? Relevant history/background? 
What would happen if this problem persists?
What's the problem's "size" (choose measurement units) -- value of solving?

### Objectives

Big picture goals (qualitative statements)

### Metrics (Key Results)

Measurements to gauge progress toward Objectives.

### Vision Statement

What will customers' lives look like when this problem is solved?

### Risks

Business value, usability, feasibility/implementation, ...


## Scope and Limitations

### Major Benefits to Customers

Probably a list. Prefer to frame customer benefits versus "features",
which may or may not deliver customer value.

### Limitations and Exclusions

What _won't_ this product deliver, which customers may be thinking about?


## Business Context

### Stakeholder Profiles

Who are these folks, and what do they care about? Their incentives?

### Project Priorities

How will the project balance core dimensions: 
schedule, features, quality, staff, cost?
What are the baseline expectations, constraints, 
and pockets of flexibility (degrees of freedom)?

### Deployment Considerations

How will users interact with this solution? 
To satisfy that expectation, how must this product be deployed?